# fly.toml app configuration file generated for java-spring-api-agrix on 2024-02-27T09:21:38-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'java-spring-api-agrix'
primary_region = 'gru'

swap_size_mb = 512

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
